# Generated by Django 5.1.5 on 2025-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('product_price', models.PositiveIntegerField(verbose_name='Цена продукта (в копейках)')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта в Stripe')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID цены в Stripe')),
                ('stripe_session_url', models.URLField(blank=True, null=True, verbose_name='URL сессии оплаты в Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
